Model:
    name: "All_in_one_SegNet" # 模型名称
    channels: 256
    output_stride: 16
    pretrained: True

Train:
    Dataset:
        type: "SegDataset"
        root: "data/Microscopy_TrainDataset"      #   训练数据集
        transform_list:
            resize: 
                size: [352, 352]
            random_scale_crop:
                range: [0.75, 1.25]
            random_flip:
                lr: True
                ud: True
            random_rotate:
                range: [0, 359]
            random_image_enhance:
                methods: ['contrast', 'sharpness', 'brightness']
            random_dilation_erosion:
                kernel_range: [2, 5]
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        batch_size: 16
        shuffle: True
        num_workers: 8
        pin_memory: False
    Optimizer:
        type: "Adam"
        lr: 1.0e-04
        weight_decay: 0.0
        clip: 0.5
        mixed_precision: False
    Scheduler:
        type: "PolyLr"
        epoch: 50  # 迭代epoch轮数  240
        gamma: 0.9
        minimum_lr: 1.0e-07
        warmup_iteration: 300
    Checkpoint:
        checkpoint_epoch: 50  # 训练轮数
        checkpoint_dir: "snapshots/Microscopy"  # 权重保存路径
    
Test:
    Dataset:
        type: "SegDataset"
        root: "data/Microscopy_TestDataset"     #   测试数据集根目录
        testsets: ['DSB2018']
        transform_list:
            resize:
                size: [352, 352]
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "snapshots/Microscopy"   # 权重路径

Eval:
    gt_root: "data/Microscopy_TestDataset"   # 根目录
    pred_root: "snapshots/Microscopy"   # 分割结果路径
    result_path: "results/Microscopy"
    datasets: ['DSB2018']  # 测试集---DSB2018
    metrics: ['meanDic', 'meanIoU', 'wFm', 'Sm', 'meanEm', 'mae', 'maxEm', 'maxDic', 'maxIoU', 'meanSen', 'maxSen', 'meanSpe', 'maxSpe']



###### -------Microscopy-----------###########
#  # 使用单个命令进行训练、测试和评估：
#  # 单个 GPU
#  CUDA_VISIBLE_DEVICES=0 python Expr.py --config configs/Microscopy.yaml --verbose --debug

#  # 多个 GPU
#  CUDA_VISIBLE_DEVICES=0,1 python -m torchrun --nproc_per_node 2 Expr.py --config configs/Microscopy.yaml --verbose --debug



#  ### 测试
#  python run/Test.py --config configs/Microscopy.yaml --verbose

#  ### 评估
#  python run/Eval.py --config configs/Microscopy.yaml --verbose


